version: "3.8"
services:
  db:
    container_name: db_service
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db_service